[theme]
base = "light"
primaryColor = "#0F766E"
backgroundColor = "#EEF1F4"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#2A3742"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
